// Secrets aren't declared in wrangler.jsonc, so they don't show up in the
// Env type generated by `wrangler types`. Augment it here.
declare namespace Cloudflare {
  interface Env {
    SLACK_SIGNING_SECRET: string;
    SLACK_BOT_TOKEN: string;
  }
}
